### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by julicarlomagno** [NicolasPrados/MercadoLiebreTP1#1]
1- Cumple (tiene todas las secciones requeridas)
2- Cumple (el contenido de los artículos está centrado y los tamaños son correctos)
3- Cumple (el sitio se adapta a distintas resoluciones de pantalla)
4- Cumple (cuenta con un formulario de registro de usuarios)
5- Cumple (cuenta con un formulario de login)
6-
7- Cumple (el search bar es un formulario)
8- Cumple (utiliza propiedades de transición de css)
9- A mi criterio está todo muy bien logrado en este sitio.
10- No encuentro nada que necesite mejorar.

**Comment by NicolasPrados** [comment]
Muchas gracias!!
