### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by PaulaRaventos** [NicolasPrados/MercadoLiebreTP1#2]
Hola Nico!! Cómo estás?

Paso a comentarte lo que evalué en tu MercadoLiebre según lo que se pedía:

(1):  Cumple con todas las secciones requeridas
(2):  Cumple con los tamaños y esta centrado
(3):  Cumple , el sitio se adapta a distintas resoluciones de pantalla
(4)  Cumple, el sitio si cuenta con un formulario de registro para usuarios
(5)  Cumple, el sitio si cuenta con un formulario de login
(6)  Cumple, el search bar si es un formulario
(7)  Si, se utilizan transiciones y propiedades de css
(8) En mi opinión, los breakpoints quedaron excelentes en cuanto a su transición de unos a otros. Muy buena!
(9) No cambiaría nada

Excelente trabajo!!!!!

**Comment by NicolasPrados** [comment]
Muchisimas gracias Pau!!!
