### ISSUE TITLE
Peer review 

### ISSUE THREAD

**Issue by Emiliano-22** [NicolasPrados/MercadoLiebreTP1#3]
(1): ✔️ Cumple con todas las secciones requeridas
(2): ✔️ Cumple con los tamaños y esta centrado
(3): ✔️ Cumple , el sitio si se adapta a distintas resoluciones de pantalla 
(4) ✔️ El sitio si cuenta con un formulario para el registro de usuarios
(5) ✔️ El sitio si cuenta con un formulario de login
(6) ✔️ El search bar es un formulario
(7) ✔️ Si , se utilizan propiedades y transiciones de css
(8)  En general la pagina esta muy bien
(9) No tengo nada para cambiar.

muy buen trabajo y perdon por la tardanza de la review !! 🥇

**Comment by NicolasPrados** [comment]
Muchas gracias Emi, no hay drama con la demora =)
